# Generated by Django 2.2.5 on 2020-01-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('hod_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('form_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('five', models.IntegerField()),
                ('four', models.IntegerField()),
                ('three', models.IntegerField()),
                ('two', models.IntegerField()),
                ('one', models.IntegerField()),
                ('result', models.FloatField()),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback_System.Faculty')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Feedback_System.Subject')),
            ],
        ),
    ]
